# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import product_pb2 as product__pb2


class ScrapeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProductResponse = channel.unary_unary(
                '/ScrapeService/ProductResponse',
                request_serializer=product__pb2.ProductRequest.SerializeToString,
                response_deserializer=product__pb2.Products.FromString,
                )


class ScrapeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProductResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScrapeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProductResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.ProductResponse,
                    request_deserializer=product__pb2.ProductRequest.FromString,
                    response_serializer=product__pb2.Products.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ScrapeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScrapeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProductResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ScrapeService/ProductResponse',
            product__pb2.ProductRequest.SerializeToString,
            product__pb2.Products.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
