# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\x87\x01\n\x07Product\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06rating\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x66\x65\x65\x64\x42\x61\x63k\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x12\n\x05price\x18\x04 \x01(\x02H\x03\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_ratingB\x0b\n\t_feedBackB\x08\n\x06_price\"\x10\n\x0eProductRequest\"%\n\x08Products\x12\x19\n\x07product\x18\x01 \x03(\x0b\x32\x08.Product2>\n\rScrapeService\x12-\n\x0fProductResponse\x12\x0f.ProductRequest\x1a\t.Productsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=18
  _globals['_PRODUCT']._serialized_end=153
  _globals['_PRODUCTREQUEST']._serialized_start=155
  _globals['_PRODUCTREQUEST']._serialized_end=171
  _globals['_PRODUCTS']._serialized_start=173
  _globals['_PRODUCTS']._serialized_end=210
  _globals['_SCRAPESERVICE']._serialized_start=212
  _globals['_SCRAPESERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
